# Basic Docker Compose
version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app # Mount the app directory for development
      - ./backend/app_data.sqlite:/app/app_data.sqlite # Persist SQLite DB, ensure path matches AUX_DB_NAME if it's just a filename
    env_file:
      - ./.env # Load environment variables from .env file in the project root
  #   environment:
  #     - DB_HOST=your_db_host # Can also be set directly, but env_file is preferred
  #     - DB_USER=your_db_user
  #     - DB_PASSWORD=your_db_password
  #     - DB_NAME=auth
  # frontend_nginx: # This service will serve the React app and proxy to backend
  #   build: ./frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
